force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LoanReminderScheduler.cls
global class LoanReminderScheduler implements Schedulable {

	global void execute(SchedulableContext sc) {
    	List<Loan__c> loansToRemind = [SELECT Id, Due_Date__c, Member__r.Email__c
                                   	FROM Loan__c
                                   	WHERE Due_Date__c = :Date.today().addDays(1)];

    	if (!loansToRemind.isEmpty()) {
        	for (Loan__c loan : loansToRemind) {
            	System.debug('Reminder: Book Loan ID: ' + loan.Id);
            	System.debug('Due Date: ' + loan.Due_Date__c);
            	System.debug('Member Email: ' + loan.Member__r.Email__c);
            	System.debug('Message: Dear Member, your book is due tomorrow. Please return it on time to avoid fines.');
        	}
    	} else {
        	System.debug('No loans found that are due tomorrow.');
    	}
	}
}