force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Loan_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Status__c</fullName>
    <label>Loan Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Borrowed</fullName>
                <default>true</default>
                <label>Borrowed</label>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OverdueLoanReminderScheduler.cls
global class OverdueLoanReminderScheduler implements Schedulable {

	global void execute(SchedulableContext sc) {
    	// Query overdue loans
    	List<Loan__c> overdueLoans = [SELECT Id, Due_Date__c, Member__r.Email__c
                                  	FROM Loan__c
                                  	WHERE Loan_Status__c = 'Overdue'];

    	if (!overdueLoans.isEmpty()) {
        	for (Loan__c loan : overdueLoans) {
            	System.debug('Reminder: Overdue Book Loan ID: ' + loan.Id);
            	System.debug('Due Date: ' + loan.Due_Date__c);
            	System.debug('Member Email: ' + loan.Member__r.Email__c);
            	System.debug('Message: Dear Member, your book is overdue. Please return it ASAP to avoid additional fines.');
        	}
    	} else {
        	System.debug('No overdue loans found.');
    	}
	}
}